# Generated by Django 2.2 on 2020-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200601_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播商品', 'verbose_name_plural': '轮播商品'},
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], default=1, help_text='类别类型', max_length=10, verbose_name='类别类型'),
        ),
    ]
